config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'

  resources :authors
  resources :books

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books

end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def edit
    @author = Author.find(params[:id])
  end

  def create
    @author = Author.new(author_params)

    @author.save
    redirect_to @author
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to authors_path
  end

  private
    def author_params
      params.require(:author).permit(:first_name, :last_name, :date_of_birth)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @authors = Author.all
  end

  def edit
    @book = Book.find(params[:id])
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)

    @book.save
    redirect_to @book
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, author_ids: [])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
  def author_name(author)
    "#{author.first_name} " + "#{author.last_name}"
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authors/_form.html.erb
<%= form_with model: @author, local: true do |form| %>
  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </p>

  <p>
    <%= form.label :date_of_birth %><br>
    <%= form.date_select :date_of_birth %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', :back %>
<%= link_to "Home page", welcome_index_path %>

app/views/authors/edit.html.erb
<h1> Edit Author</h1>
<%= render 'form' %>

app/views/authors/index.html.erb
<% if @authors.present? %>
  <table style="width:50%">
    <tr>
      <th>Author Name</th>
      <th>DOB</th>
    </tr>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author_name(author) %></td>
        <td><%= author.date_of_birth %></td>
        <td><%= link_to 'Show', author_path(author.id) %></td>
        <td><%= link_to 'Edit', edit_author_path(author.id) %></td>
        <td><%= link_to 'Delete', author_path(author.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h3>There is no author added yet. Please first add author.</h3>
  <h3><%= link_to 'Add Author', new_author_path %></h3>
<% end %>
<br>
<%= link_to 'Back', :back %>
<%= link_to "Home page", welcome_index_path %>

app/views/authors/new.html.erb
<h1> New Author</h1>
<%= render 'form' %>

app/views/authors/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @author.last_name %>
</p>

<p>
  <strong>DOB:</strong>
  <%= @author.date_of_birth %>
</p>

<p>
  <strong>Book List:</strong>
  <% @author.books.each do |book| %>
    <ul>
      <li><%= link_to book.title, book_path(book.id), title: 'Book detail' %></li>
    </ul>
  <% end %>
</p>
<%= link_to 'Back', :back %>
<%= link_to "Home page", welcome_index_path %>

app/views/books/_authors.html.erb
<div class="author-type">
  <p>
    <%= title %>
  </p>
</div>
<div class="checkbox-authors">
  <% authors.to_a.each do |author| %>
    <% selected = f.object&.author_ids&.include?(author.id) %>
    <label>
      <%= author_name(author) %>
      <%= check_box_tag 'book[author_ids][]', author.id, selected %>
    </label>
  <%end%>
</div>

app/views/books/_book_form.html.erb
<%= form_with model: @book, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <%= render partial: 'authors', locals: { title: 'Author Name', authors: @authors, f: form } %>

  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', :back %>
<%= link_to "Home page", welcome_index_path %>

app/views/books/edit.html.erb
<h1> Edit Book</h1>
<%= render 'book_form' %>

app/views/books/index.html.erb
<% if @books.present? %>
  <table style="width:50%">
    <tr>
      <th>Title</th>
    </tr>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= link_to 'Show', book_path(book.id) %></td>
        <td><%= link_to 'Edit', edit_book_path(book.id) %></td>
        <td><%= link_to 'Delete', book_path(book.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
  <br>
<% else %>
  <h3>There is no book added yet. Please first add books..</h3>
  <h3><%= link_to 'Add Book', new_book_path %></h3>
<% end %>
<%= link_to 'Back', :back %>
<%= link_to "Home page", welcome_index_path %>

app/views/books/new.html.erb
<h1> New Book</h1>
<%= render 'book_form' %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
<p>
  <strong>Authors:</strong>
  <% @book.authors.each do |author| %>
    <ul>
      <li><%= link_to author_name(author), author_path(author), title: 'Author Detail' %></li>
    </ul>
  <% end %>
</p>
<%= link_to 'Back', :back %>
<%= link_to "Home page", welcome_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthorsAndBooks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class='home'>
  <h3><%= link_to 'Add Author', new_author_path %></h3>
  <h3><%= link_to 'Add Book', new_book_path%></h3>
  <h3><%= link_to 'Authors List', authors_path %></h3>
  <h3><%= link_to 'Books List', books_path  %></h3>
</div>
<%= stylesheet_link_tag "welcome" %>